services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    volumes:
      - ./db:/data/db

  redis:
    image: redis
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}

  server:
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_DOCKER_PORT=${MONGODB_DOCKER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DOCKER_PORT=${REDIS_DOCKER_PORT}
      - BUN_LOCAL_PORT=${BUN_LOCAL_PORT}
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /usr/src/bun-app/node_modules
      - ./server:/usr/src/bun-app
    ports:
      - ${BUN_LOCAL_PORT}:${BUN_DOCKER_PORT}

  nginx:
    depends_on:
      - server
    environment:
      - BUN_LOCAL_PORT=${BUN_LOCAL_PORT}
      - NGINX_DOCKER_PORT=${NGINX_DOCKER_PORT}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_LOCAL_PORT}:${NGINX_DOCKER_PORT}

  client:
    depends_on:
      - nginx
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /usr/src/react-app/node_modules
      - ./client:/usr/src/react-app
    ports:
      - ${VITE_APP_LOCAL_PORT}:${VITE_APP_DOCKER_PORT}
